### PR TITLE
support command methods in "Auto-sort collections by product properties"

### PR DESCRIPTION
**Pull request by isaacbowen**
A user was looking to sort products by SKU, which means sorting by these lookups:

1. `variants`
2. `first`
3. `sku`

Turns out `first` is a [command method](https://github.com/Shopify/liquid/blob/86605016e15e3670c1cc74d75012f9e4bdcb4de2/lib/liquid/variable_lookup.rb#L5), and those [cannot be invoked with bracket notation](https://github.com/Shopify/liquid/blob/86605016e15e3670c1cc74d75012f9e4bdcb4de2/lib/liquid/variable_lookup.rb#L27-L31). So, I'm adding a switch here to support their use. (This is safe for instances where we actually _would_ be looking for an object property called "first", because anything supported by a bracket lookup is also supported with a dot lookup, to my knowledge.)

### CODE REVIEW

**Comment by isaacbowen** [comment]
@tekhaus Can you sanity-check me on this one?

**Comment by tekhaus** [comment]
This does work in my testing. Interestingly though, because SKUs can be blank, products without SKUs will be _usually_ be sorted to the top since an empty string comes before any characters in a Liquid sort. I say usually, because if an empty SKU is in fact a null value, then that will be sorted last.

```
"sorted_product_values": [
  {
    "id": "gid://shopify/Product/7629446938872",
    "value": ""
  },
  {
    "id": "gid://shopify/Product/7629446906104",
    "value": ""
  },
  {
    "id": "gid://shopify/Product/7629446381816",
    "value": "BED-TABLE-01"
  },
  {
    "id": "gid://shopify/Product/7629447069944",
    "value": "CLAY-POT-R"
  },
  {
    "id": "gid://shopify/Product/7629447004408",
    "value": "CREAM-SOFA"
  },
  {
    "id": "gid://shopify/Product/7629447037176",
    "value": null
  }
]
```

**Comment by isaacbowen** [comment]
> A compact filter for arrays which removed nils and empty strings would be great here ;)

There's prior art for this!

https://api.rubyonrails.org/v7.0.3/classes/Enumerable.html#method-i-compact_blank

**Comment by isaacbowen** [comment]
> Interestingly though, because SKUs can be blank, products without SKUs will usually be sorted to the top since an empty string comes before any characters in a Liquid sort. I say usually, because if an empty SKU is in fact a null value, then that will be sorted last.

I think I've got that solved in [dc27f48](https://github.com/lightward/mechanic-tasks/pull/145/commits/dc27f4865f8eb7dbcc8577001801482f4283b337), coercing empty strings to nil so that all empty SKUs (be they empty strings or literal nils/nulls) get sorted to the end.

**Comment by tekhaus** [comment]
> I think I've got that solved in [dc27f48](https://github.com/lightward/mechanic-tasks/pull/145/commits/dc27f4865f8eb7dbcc8577001801482f4283b337), coercing empty strings to nil so that all empty SKUs (be they empty strings or literal nils/nulls) get sorted to the end.

works perfectly 👍

**Pull request merged**
