### PR TITLE
Fix for missing boolean flag on schedule option

### PR DESCRIPTION
**Pull request by bluec**
Hi, I noticed this small issue with the "Tag products with no images" task.

I hope this PR is correct. Let me know if anything is amiss.

(Great work on Mechanic, it is an ingenious and elegant system!)

### CODE REVIEW

**Comment by bluec** [comment]
recheck

**Comment by isaacbowen** [comment]
Hey @bluec! Thanks for this - your change looks exactly correct, and I appreciate you putting this in. :)

The CLA bot is... it needs work, hehe. Please copy and paste the below as a comment, by itself, on this pr:

> I have read the CLA Document and I hereby sign the CLA

That should clear the CLA check. :)

**Comment by bluec** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by isaacbowen** [comment]
Awesome - thanks a ton. :D

**Comment by mattsodomsky** [comment]
@bluec - congrats on joining the contributor's list! YAY!

**Pull request merged**
